name: Build And Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs: 
  buildAndTest:
    runs-on: ubuntu-latest
    
    env:
        TOKEN: ${{ secrets.TOKEN }}
        FUNCTION_ENDPOINT: ${{ secrets.FUNCTION_ENDPOINT }}
        
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore
